### ISSUE TITLE
Enhance MetricsHub ConnectorStore Loading System

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#170]
# Current System
Currently, MetricsHub parses connectors (YAML files) at startup. These connectors may specify external awk scripts that the engine loads and executes at runtime to process query results. A connector can dictate the execution logic to its associated external files.

# Enhancements
The proposed enhancements aim to internalize the connectors and their associated external files into a serialized format within a JAR artifact. **metricshub-community-connectors-extension.jar**.

**Improved Performance**: By internalizing YAML connectors, scripts and external files, the engine reduces I/O operations at runtime.
**Enhanced Security**: Encapsulating scripts within the JAR limits exposure to unauthorized modifications.
**Simplified Deployment**: Distributing connectors as a part of a JAR file simplifies the deployment process.

# Detailed Changes

## Connector Serialization
We need to serialize the ConnectorStore object that encapsulates all connector objects.

1. Each connector object within the ConnectorStore will contain a `Map<String, EmbeddedFile>` for storing associated external files (e.g., awk scripts).
2. Serialize the ConnectorStore object into a JAR artifact, named **metricshub-community-connectors-extension.jar**.
3. The MetricsHub engine will be adjusted to load embedded files from memory (Connector object) rather than external files from the OS.

## Connector Loading via Extension Interface:

1. We have already defined the `IConnectorStoreProviderExtension` with a method `getConnectorStore()` that, when implemented, provides the deserialized `ConnectorStore` object from the JAR artifact.
2. At runtime, the MetricsHub engine will dynamically load this JAR artifact and retrieve the `ConnectorStore` using the `IConnectorStoreProviderExtension` interface through the `ExtensionLoader` and the `ExtensionManager`.

## MetricsHub Agent Adjustments

* Modify the MetricsHub Agent to load available **ConnectorStore** extensions at startup.
* Retain the functionality to read connectors from the filesystem **connectors** directory, allowing support teams to override and test connector updates directly with users in production environments.

**Comment by bertysentry** [comment]
Looks good!

A few questions and comments, or suggestions:

* `BinaryConnectorStoreProvider` may be implemented only in Enterprise, and the Community Edition keeps the basic mechanism where everything is loaded from the filesystem. This way, the Community edition remains completely open and free to hack around (by editing the YAML files directly).
* If I understand correctly, `FilesystemConnectorStoreProvider` reads the YAML files as well as the external files referenced in the YAML, and produce a store of `Connector` objects, which will embed the external files. Question: Such embedded files should be stored as *String*... or as *ByteArray* to allow the developer to include binary files, or specific text encoding? TBD...

Thanks!

**Comment by NassimBtk** [comment]
Thanks @bertysentry for the comments and suggestions.
Here is what we discussed in orally😉
Indeed Community Edition will keep the current behavior of the Connector Store reader, so that users retain full control over the community connectors in production.
For the embedded file format, yes, it can be stored as a byte array, so that we can regenerate the original file if needed. When executing the _awk_ compute, we convert the embedded file content (awk script) to text using UTF-8.
