### ISSUE TITLE
The coverage in MetricsHub shown in Prometheus is not accurate

### ISSUE THREAD

**Issue by MedMaalej** [sentrysoftware/metricshub#370]
In Prometheus Dashborads, we display a percentage of coverage, which means the hosts that are really monitored compared to the hosts that are configured (in the YAML file `metricshub.yaml`).

The percentage of coverage in MetricsHub is very variable compared to HWS, the metric `metricshub_connector_status` value is not accurate.

The coverage in Metricshub  changes from 18% to more than 90% at once. In HWS, it's mostly between 95% and 97 %.

Some hosts are sometimes monitored and sometimes not monitored.
 

-  `metricshub_connector_status` in Metricshub:

![image (5)](https://github.com/user-attachments/assets/db649f23-01e9-4427-878f-c15a49d97048)

-  `hardware_sentry_connector_status` in HWS:

![image (6)](https://github.com/user-attachments/assets/0411db82-f34c-44cb-ab15-9bafe00f65b6)

Here is an example of the problem occurring with the host `anaxagore ` (windows):

- In MetricsHub

![image](https://github.com/user-attachments/assets/da6c60de-1d6e-48e8-b02a-bd3c1315adcb)

- In HWS

![image (1)](https://github.com/user-attachments/assets/7342bac7-880e-46e5-b12a-f26bb18c405e)

We need to find the root cause and fix the problem

**Comment by NassimBtk** [comment]
We should write a KB article as well as an update in the https://metricshub.com/docs/latest/guides/quick-start-community-prometheus.html to explain how to tune the query time window using `--query.lookback-delta=<time>`

**Comment by NassimBtk** [comment]
This really depends on many factors, the MetricsHub collect period, machine load, Grafana PromQL Settings,  Prometheus, …etc. It is better to write a KBA to explain the behavior as well as all the possible solutions.
