### ISSUE TITLE
Wbem issues with some hosts on MetricsHub [Potential bug]

### ISSUE THREAD

**Issue by MedMaalej** [sentrysoftware/metricshub#375]
On Matsya **module-metricshub**, Wbem queries fail with some hosts.

Here is an example of a failing query sent **by Hardware Sentry KM to Matsya module-metricshub** (host : **hp3par-san**)

```
<MetricsHubOperation>
  <Host>hp3par-san</Host>
  <Id>hp3par-san</Id>
  <hostType>Storage</hostType>
  <ExcludedConnectors></ExcludedConnectors>
  <SelectedConnectors></SelectedConnectors>
  <WBEM>
    <Username>#########</Username>
    <Password>######### </Password>
    <Protocol>https</Protocol>
    <Port>5989</Port>
    <Timeout>120</Timeout>
  </WBEM>
  <OperationType>Discovery</OperationType>
  <LogFile></LogFile>
</MetricsHubOperation>
```

No connectors detected on Metricshub CLI and MetricsHub Agent:

<img width="943" alt="h3par" src="https://github.com/user-attachments/assets/75fd3d4b-e9d7-4ef8-ac09-5fa49a4e591a">

In Metricshub logs, here is a screenshot showing the exception found after running the above command:

![wbemException](https://github.com/user-attachments/assets/c52cdf21-a993-4190-bb40-d61696592f45)

The same problem was reported with the host **eternus-i0**

We have to double check Wbem processing on MetricsHub.

**Comment by MedMaalej** [comment]
I double-checked the cause of the SSL Handshake exception on **eternus-i0**.
After modifying the java.security file under  **C:\Program Files\MetricsHub\runtime\conf\security** by commenting some lines that disable TLS algorithms, MetricsHub was able to collect the monitors ( 27 monitors including the Host and the Connector monitors ).

Here is the metricshub command on Metricshub CLI:

`metricshub eternus-i0 -t storage --wbem --wbem-username **** --wbem-password ****
`

Here is the result:

<img width="952" alt="eternus2" src="https://github.com/user-attachments/assets/e09110ef-eb7e-483c-9460-8e53745964ca">



To confirm the Metricshub result, I also tested on the KM ( 25 monitors were collected, the connector and the host were excluded by default).

![Capture d'écran 2024-12-09 174658](https://github.com/user-attachments/assets/bfa003bb-058e-402a-88ac-43cbd912fb54)

![Capture d'écran 2024-12-09 174646](https://github.com/user-attachments/assets/de6151eb-ee2a-4eb5-ac1e-6773a323cb81)

That being said, the SSL handshake issues come from the Java/JDK security policy that blocks some protocols and/or algorithms.

 ℹ️No changes need to be implemented on Metricshub since the problem did not came from our code.

**Comment by NassimBtk** [comment]
Problem related to the deprecated SSL versions.
