### ISSUE TITLE
Don't report `hw.status{state="present"}` for `cpu` monitors discovered by Linux and Window connectors

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/metricshub#412]
**Proposal**

The missing device detection in `HardwarePostDiscoveryStrategy` should exclude monitors discovered from connectors that lack the `hardware` tag.

**Comment by MedMaalej** [comment]
I tested the fix locally on my computer. The tests covered those cases:

- A Linux host containing hardware monitors (using the host: **babbage**)

Grafana should not display any hw.status metric at all. 

<img width="958" alt="testStatusBabbage" src="https://github.com/user-attachments/assets/52f0fa4b-1499-4d26-8e33-afccdaf9dfa5">

- A Windows host containing hardware monitors (using the host: **WinStorageSpaces**)

**Grafana should display hw.status metric for all nonendpoint host monitors for which the connector has "hardware" tag.
For endpoint host monitors, only the endpoint hosts having at least one connector monitor having "hardware" tag.**

<img width="934" alt="testStatusWinStorageConnector" src="https://github.com/user-attachments/assets/33f18940-d704-48fa-8f96-b580f200de34">

<img width="920" alt="testStatusWinStorageDiskController" src="https://github.com/user-attachments/assets/a6ce65dd-80fd-4610-8226-249f155b450a">

<img width="956" alt="testStatusWinStorageHost" src="https://github.com/user-attachments/assets/579836c1-d34e-44ce-b758-187b6eb0faff">

<img width="923" alt="testStatusWinStorageLogicalDisk" src="https://github.com/user-attachments/assets/ff042669-a287-47cc-9832-fac18c6e646a">

<img width="953" alt="testStatusWinStoragePhysicalDik" src="https://github.com/user-attachments/assets/e5334ff7-338f-4bb8-a688-2c08f79d2fce">
